package shop.abcommerce.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccountUAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountUAllPropertiesEquals(AccountU expected, AccountU actual) {
        assertAccountUAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountUAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountUAllUpdatablePropertiesEquals(AccountU expected, AccountU actual) {
        assertAccountUUpdatableFieldsEquals(expected, actual);
        assertAccountUUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountUAutoGeneratedPropertiesEquals(AccountU expected, AccountU actual) {
        assertThat(actual)
            .as("Verify AccountU auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountUUpdatableFieldsEquals(AccountU expected, AccountU actual) {
        assertThat(actual)
            .as("Verify AccountU relevant properties")
            .satisfies(a -> assertThat(a.getDocumentNumber()).as("check documentNumber").isEqualTo(expected.getDocumentNumber()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getSecondName()).as("check secondName").isEqualTo(expected.getSecondName()))
            .satisfies(a -> assertThat(a.getFirstLastName()).as("check firstLastName").isEqualTo(expected.getFirstLastName()))
            .satisfies(a -> assertThat(a.getSecondLastName()).as("check secondLastName").isEqualTo(expected.getSecondLastName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountUUpdatableRelationshipsEquals(AccountU expected, AccountU actual) {
        assertThat(actual)
            .as("Verify AccountU relationships")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
