package shop.abcommerce.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubCategoryAllPropertiesEquals(SubCategory expected, SubCategory actual) {
        assertSubCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSubCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubCategoryAllUpdatablePropertiesEquals(SubCategory expected, SubCategory actual) {
        assertSubCategoryUpdatableFieldsEquals(expected, actual);
        assertSubCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubCategoryAutoGeneratedPropertiesEquals(SubCategory expected, SubCategory actual) {
        assertThat(actual)
            .as("Verify SubCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubCategoryUpdatableFieldsEquals(SubCategory expected, SubCategory actual) {
        assertThat(actual)
            .as("Verify SubCategory relevant properties")
            .satisfies(a -> assertThat(a.getSubCategoryName()).as("check subCategoryName").isEqualTo(expected.getSubCategoryName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubCategoryUpdatableRelationshipsEquals(SubCategory expected, SubCategory actual) {
        assertThat(actual)
            .as("Verify SubCategory relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
